feat(pr-comment): remove GITHUB_TOKEN requirement

diff --git a/changeset/pr-comment/action.yml b/changeset/pr-comment/action.yml
--- a/changeset/pr-comment/action.yml
+++ b/changeset/pr-comment/action.yml
@@ -1,46 +1,50 @@
 name: Changeset PR Comment
 description: Add a comment to a PR if a changeset is not present
+
 inputs:
   message:
-    default: 'Hey! Remember to add a changeset with `pnpm changeset add` to describe your changes for versioning.'
     description: The message to comment on the PR
+    default: 'Hey! Remember to add a changeset with `pnpm changeset add` to describe your changes for versioning.'
+
 runs:
   using: composite
   steps:
-    - name: Check if GITHUB_TOKEN is set
-      if: env.GITHUB_TOKEN == ''
+    - name: Check required tools
       shell: bash
       run: |
-        echo "No GITHUB_TOKEN environment variable set"
-        exit 1
+        command -v gh >/dev/null 2>&1 || {
+          echo "GitHub CLI (gh) is required"
+          exit 1
+        }
+
+        command -v jq >/dev/null 2>&1 || {
+          echo "jq is required"
+          exit 1
+        }
 
     - name: Check if a comment already exists
       id: check_comment
       shell: bash
+      env:
+        GH_TOKEN: ${{ github.token }}
+        MESSAGE: ${{ inputs.message }}
       run: |
         PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
         echo "pr_number=$PR_NUMBER" >> "$GITHUB_ENV"
 
-        COMMENTS=$(gh pr view "$PR_NUMBER" --json comments -q ".comments[] | select(.body | index(\"${MESSAGE}\")) | .id")
+        COMMENTS=$(gh pr view "$PR_NUMBER" --json comments --jq ".comments[] | select(.body | contains(\"${MESSAGE}\")) | .id")
 
         if [ -n "$COMMENTS" ]; then
           echo "comment_exists=true" >> "$GITHUB_ENV"
-
-          echo "comment_id<<EOF" >> "$GITHUB_ENV"
-          echo "$COMMENTS" >> "$GITHUB_ENV"
-          echo "EOF" >> "$GITHUB_ENV"
         else
           echo "comment_exists=false" >> "$GITHUB_ENV"
         fi
-      env:
-        GH_TOKEN: ${{ env.GITHUB_TOKEN }}
-        MESSAGE: ${{ inputs.message }}
 
     - name: Add comment if no comment posted
       if: env.comment_exists == 'false'
       shell: bash
-      run: |
-        gh pr comment ${{ env.pr_number }} --body "$MESSAGE"
       env:
-        GH_TOKEN: ${{ env.GITHUB_TOKEN }}
+        GH_TOKEN: ${{ github.token }}
         MESSAGE: ${{ inputs.message }}
+      run: |
+        gh pr comment "$pr_number" --body "$MESSAGE"
